"""Storage backend seam — the one place the Store's DB dialect lives.

Phase 1 of the cloud data-model redesign (tracker: sonaloop/storage-backend-abstraction;
page: cloud-data-model). Open-core uses SQLite; cloud will add a Postgres backend with
row-level tenancy (sonaloop/storage-row-tenancy-and-rls). The Store and its mixins talk to
a DB-API-2.0-shaped connection and use `?` placeholders uniformly — a backend is free to
translate those (Postgres uses `%s`) so the mixins stay dialect-agnostic.

This module ships SQLite ONLY, routed through the seam with zero behaviour change. A
`postgresql://` DATABASE_URL is an explicit, loud error here — never a silent fallback —
until the Postgres backend lands.
"""
from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path
from typing import Any

from ._schema import SCHEMA


class StorageBackend:
    """Owns connection creation + schema application for one SQL dialect."""

    dialect: str = "abstract"
    #: the on-disk DB path for file backends (SQLite); None for server backends (Postgres).
    path: Path | None = None

    def connect(self) -> Any:                       # pragma: no cover - interface
        raise NotImplementedError

    def apply_schema(self, conn: Any) -> None:      # pragma: no cover - interface
        raise NotImplementedError


class SqliteBackend(StorageBackend):
    """The open-core / default backend: one local SQLite file, `sqlite3.Row` rows."""

    dialect = "sqlite"

    def __init__(self, path: Path) -> None:
        self.path = path

    def connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.path)
        conn.row_factory = sqlite3.Row
        return conn

    def apply_schema(self, conn: sqlite3.Connection) -> None:
        conn.executescript(SCHEMA)


# ----------------------------------------------------------------- Postgres dialect
# The cloud backend (tracker: sonaloop/storage-backend-abstraction). The Store's mixins are
# written in SQLite SQL — `?` placeholders, `INSERT OR REPLACE`, sqlite3.Row access. Rather
# than rewrite ~hundreds of statements, the Postgres connection TRANSLATES them on the way
# through, so the mixins stay one dialect-agnostic body. psycopg is imported lazily and is an
# OPTIONAL dependency — open-core never touches it.

_UPSERT_RE = re.compile(r"^\s*INSERT\s+OR\s+(REPLACE|IGNORE)\s+INTO\s+(\w+)\s*\(([^)]*)\)",
                        re.IGNORECASE | re.DOTALL)
_UPSERT_PREFIX_RE = re.compile(r"INSERT\s+OR\s+(?:REPLACE|IGNORE)\s+INTO", re.IGNORECASE)


def _pg_params(sql: str) -> str:
    """SQLite `?` placeholders → psycopg `%s`. `%` is escaped to `%%` first (psycopg's
    paramstyle treats it specially); the Store's SQL contains no literal `%` today."""
    return sql.replace("%", "%%").replace("?", "%s")


def schema_statements_postgres() -> list[str]:
    """Port the one SQLite SCHEMA to Postgres DDL, split into executable statements:
    drop the WAL pragma, AUTOINCREMENT → IDENTITY, BLOB → BYTEA. Everything else
    (TEXT/INTEGER/UNIQUE/PRIMARY KEY/CREATE INDEX IF NOT EXISTS, the quoted "end" column)
    is already valid Postgres. Pure function — no driver needed, so it is unit-testable."""
    # Strip `--` line comments first: some contain a ';' (e.g. "…the cursor; the table…")
    # which would corrupt a naive split. SQLite's executescript tolerates them natively.
    no_comments = "\n".join(re.sub(r"--.*$", "", line) for line in SCHEMA.splitlines())
    out: list[str] = []
    for raw in no_comments.split(";"):
        stmt = raw.strip()
        if not stmt or stmt.upper().startswith("PRAGMA"):
            continue
        stmt = stmt.replace("INTEGER PRIMARY KEY AUTOINCREMENT",
                            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        stmt = re.sub(r"\bBLOB\b", "BYTEA", stmt)
        out.append(stmt)
    return out


class _PgConnection:
    """Wraps a psycopg connection so the Store's SQLite-flavoured SQL runs unchanged:
    translates `INSERT OR REPLACE/IGNORE` → `ON CONFLICT`, `?` → `%s`, and yields dict
    rows. `execute`/`executemany` return a psycopg cursor (rowcount/fetch* as usual)."""

    def __init__(self, raw: Any) -> None:
        self._raw = raw
        self._pk: dict[str, list[str]] = {}

    def _pk_cols(self, table: str) -> list[str]:
        if table not in self._pk:
            cur = self._raw.execute(
                "SELECT a.attname FROM pg_index i "
                "JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) "
                "WHERE i.indrelid = %s::regclass AND i.indisprimary "
                "ORDER BY array_position(i.indkey, a.attnum)", (table,))
            self._pk[table] = [r["attname"] for r in cur.fetchall()]
        return self._pk[table]

    def _translate(self, sql: str) -> str:
        m = _UPSERT_RE.match(sql)
        if m:
            kind, table, collist = m.group(1).upper(), m.group(2), m.group(3)
            cols = [c.strip().strip('"') for c in collist.split(",")]
            pk = self._pk_cols(table)
            if not pk:
                raise RuntimeError(f"INSERT OR {kind} on {table!r} which has no primary key")
            target = ", ".join(f'"{c}"' for c in pk)
            base = _UPSERT_PREFIX_RE.sub("INSERT INTO", sql, count=1)
            non_pk = [c for c in cols if c not in pk]
            if kind == "IGNORE" or not non_pk:
                sql = f"{base} ON CONFLICT ({target}) DO NOTHING"
            else:
                sets = ", ".join(f'"{c}" = EXCLUDED."{c}"' for c in non_pk)
                sql = f"{base} ON CONFLICT ({target}) DO UPDATE SET {sets}"
        return _pg_params(sql)

    def execute(self, sql: str, params: tuple = ()) -> Any:
        return self._raw.execute(self._translate(sql), params)

    def executemany(self, sql: str, seq: Any) -> Any:
        cur = self._raw.cursor()
        cur.executemany(self._translate(sql), list(seq))
        return cur

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()

    def cursor(self) -> Any:
        return self._raw.cursor()


class PostgresBackend(StorageBackend):
    """The cloud backend: one shared Postgres. Single-tenant in Phase 1 (parity with
    SQLite); row-level tenancy + RLS arrive next (sonaloop/storage-row-tenancy-and-rls).
    An optional `SONALOOP_PG_SCHEMA` isolates a run into its own schema (per-test
    isolation, and the future control/tenant split)."""

    dialect = "postgres"
    path = None

    def __init__(self, dsn: str, schema: str | None = None) -> None:
        self.dsn = dsn
        self.schema = schema or os.getenv("SONALOOP_PG_SCHEMA") or None

    def connect(self) -> _PgConnection:
        import psycopg
        from psycopg.rows import dict_row

        raw = psycopg.connect(self.dsn, autocommit=False, row_factory=dict_row)
        if self.schema:
            raw.execute(f'CREATE SCHEMA IF NOT EXISTS "{self.schema}"')
            raw.execute(f'SET search_path TO "{self.schema}"')
            raw.commit()
        return _PgConnection(raw)

    def apply_schema(self, conn: _PgConnection) -> None:
        for stmt in schema_statements_postgres():
            conn._raw.execute(stmt)
        conn._raw.commit()


def make_backend(path: Path | None = None) -> StorageBackend:
    """Select the Store's backend from DATABASE_URL. Default / open-core: SQLite at `path`
    (or the partition-resolved `database_path()`). A `postgresql://` URL selects Postgres —
    never a silent SQLite fallback (a silent fallback once served the cloud app off the
    wrong store)."""
    url = os.getenv("DATABASE_URL", "")
    if url.startswith(("postgres://", "postgresql://")):
        return PostgresBackend(url)
    from ..config import database_path
    return SqliteBackend(path or database_path())
